### ISSUE TITLE
Disable only Wi-Fi

### ISSUE THREAD

**Issue by OddyAte** [jakeajames/RealCC#10]
Hello, I'd like to use RealCC on iOS 11.3.1 but I own an Apple Watch that keeps itself connected even when the bluetooth is turned off from ControlCenter (greyed out). Could you please make a version of RealCC that works just to disable the Wi-Fi?

**Comment by clubby789** [comment]
As long as you only disable Wi-Fi this shouldn't be a problem should it?

**Comment by OddyAte** [comment]
It is a problem because I want bluetooth to be grayed out... and I cannot do that because it's either enabled or disabled..

**Comment by clubby789** [comment]
https://github.com/clubby789/RealCC
If you can compile it yourself, I took out the references to Bluetooth in my fork which should fix it for you. No guarantees though, I did this very quickly.

**Comment by OddyAte** [comment]
I tried removing the Bluetooth part from the code too, I presume I did that correctly but the compiling is the issue. I never did this and I followed a few tutorials but all of them seem pretty difficult and they need so many steps to be followed. That's why I opened this toppic, I am sure there are a lot of people that would be intrested in disabling only the Wi-Fi (sepparate tweak) or a settings page where you can enable/disable either one of them

**Comment by clubby789** [comment]
Do you have Theos installed on your device?
If so:
0. Run `su` and log in as root
1. Run `mkdir /var/mobile/TheosProjects`
2. Run `cd /var/mobile/TheosProjects`
3. Run `git clone -b patch-2 https://github.com/clubby789/RealCC/
4. `cd RealCC`
5. `make package install`

EDIT: Don't do this actually, I'll compile it for you

**Comment by OddyAte** [comment]
I will try again now, I don't have theos, I installed cygwin on windows and after that the tutorial went for ios8 sdk and I wasn't sure if that's ok. I will try again

**Comment by clubby789** [comment]
I've compiled it for you. Download https://github.com/clubby789/RealCC/blob/no-bt/com.jakeashacks.realcc_0.0.5-1%2Bdebug_iphoneos-arm.deb, put it in /var/mobile/Downloads, then use files to install it.

**Comment by OddyAte** [comment]
I tried installing it with Filza and it gives me an error. (bash: Filza: command not found)

**Comment by clubby789** [comment]
Run in Terminal:
`dpkg -i /var/mobile/Downloads/com.jakeashacks.realcc_0.0.5-1+debug_iphoneos-arm.deb`
Use su to log in as root first

**Comment by OddyAte** [comment]
I managed to get Theos up and running and apparently there are errors in the code. I will try to correct them if I can, I'll be back with an answer
Tweak.xm:25: error: %end does not make sense inside a block
Update: missing }, now it compiles, linking does not work, I will try to fix this as well cuz it got me hooked now 😆 
Update 2: had to change SDK to 8.1, now the only problem is connecting to my iPhone

**Comment by clubby789** [comment]
The version on my Git is outdated, you're better off using DPKG to install the deb

**Comment by OddyAte** [comment]
I managed to set everything up and use Cygwin to install your no-bt branch, everything went flawlessly and the tweak works ❤️ Thank you so much for the help and getting me to be stubborn about these errors and not give up 😆 I really think people would  download this tweak from cydia, I've seen that most youtubers include it in their top tweak list, and many of us have an Apple Watch.

**Comment by clubby789** [comment]
Haha no problem. I might ask the dev if he'd be okay with me uploading this and crediting him

**Comment by clubby789** [comment]
By the way you should probably close this issue now
