### ISSUE TITLE
Fix for wifi and WLAN issue.

### ISSUE THREAD

**Issue by Namouk** [jakeajames/RealCC#5]
@jakeajames @Packetfahrer

Your last update (0.0.1-14) still doesn't work for phones displaying WLAN instead of wifi in the settings.

To fix it you need to change

`localizedStringForKey:@"CONTROL_CENTER_STATUS_WIFI_NAME"`

to

`localizedStringForKey:@"CONTROL_CENTER_STATUS_WLAN_NAME"`

I can confirm it works just as intended.

Thanks for this great tweak!

**Comment by Packetfahrer** [comment]
Should fixed in PR.

**Comment by Namouk** [comment]
I've got mine working already, but looking forward for the final release.Thanks!

**Comment by jakeajames** [comment]
@Namouk i checked the language file of german and the localization is ok, CONTROL_CENTER_STATUS_WIFI_NAME is equal to WLAN

**Comment by Namouk** [comment]
My language is set to English (I tried all the English languages available and it's the same) and the 0.0.4-1 doesn't work if you don't change  it to CONTROL_CENTER_STATUS_WLAN_NAME.

**Comment by Packetfahrer** [comment]
I tried this with 3 Devices  and it worked !

**Comment by Namouk** [comment]
Are you talking about the 0.0.4-1? If not, can you provide a link to a binary that I can try? I could tell you right away if it works.

**Comment by Packetfahrer** [comment]
yes 0..0.4-1

**Comment by Namouk** [comment]
That's odd because that's the version I had to patch with some hex editor to get the Wifi to work on my Phone used in Hong Kong (Bluetooth works perfectly without patching).

**Comment by Packetfahrer** [comment]
strange but why should apple use a German Value as Standard. Check this tomorrow again.

**Comment by Namouk** [comment]
That's basically my language settings.

https://i.imgur.com/D2b7f7a.png

**Comment by Packetfahrer** [comment]
Oh seems I was really wrong  :) !
Fix is in PR.


<img width="563" alt="bildschirmfoto 2018-01-29 um 13 00 02" src="https://user-images.githubusercontent.com/963953/35509489-98759696-04f4-11e8-8859-1f39dfc1a4d7.png">

**Comment by Namouk** [comment]
I knew I wasn't dreaming! :)

**Comment by Packetfahrer** [comment]
Pull Request is done ;) thank You 👍

**Comment by Namouk** [comment]
Bitte schön! ;)
